import SmoothScroll from "@/components/SmoothScroll";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Infinite Scroll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`{inter.className} w-[60%] mx-auto`}>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
